name: CI

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}  # ώστε το 'src' να είναι ορατό όπου χρειαστεί

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install test deps
        run: pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Byte-compile sources
        run: python -m compileall -q src

      - name: Smoke import (fallback)
        run: |
          python - << 'PY'
          try:
              from importlib import import_module
              import_module("src.ultra_lottery_helper")
              print("Imported via package path.")
          except Exception as e:
              print("Package import failed, falling back to runpy:", e)
              import runpy, pathlib
              runpy.run_path(str(pathlib.Path("src")/"ultra_lottery_helper.py"), run_name="not_main")
              print("Loaded via runpy OK.")
          PY
