name: CI

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 👉 Extra Step 1: Install test dependencies
      - name: Install test deps
        run: pip install pytest

      # 👉 Extra Step 2: Run tests
      - name: Run tests
        run: pytest -q

      # Γρήγορος έλεγχος σύνταξης: byte-compile
      - name: Byte-compile sources
        run: python -m compileall -q src

      # Smoke test: απλό import χωρίς εκκίνηση Gradio UI
      - name: Smoke import
        run: |
          python - << 'PY'
          from importlib import import_module
          m = import_module("src.ultra_lottery_helper")
          print("Imported ultra_lottery_helper OK (v6.3.0).")
          PY
