name: CI

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}   # για να φαίνεται το 'src' ως package root
      QT_QPA_PLATFORM: offscreen            # headless Qt
      MPLBACKEND: Agg                       # headless matplotlib

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install test deps (pytest)
        run: pip install pytest

      - name: Run tests (if tests/ exists)
        run: |
          if [ -d tests ]; then
            echo "Running pytest..."
            pytest -q
          else
            echo "No tests/ directory; skipping pytest."
          fi

      - name: Byte-compile sources
        run: |
          if [ -d src ]; then
            python -m compileall -q src
          fi

      - name: Smoke import — core module
        run: |
          python - << 'PY'
          import sys, os
          sys.path.insert(0, os.getcwd())
          import importlib
          importlib.import_module("src.ultra_lottery_helper")
          print("OK: imported src.ultra_lottery_helper")
          PY

      - name: Smoke import — desktop UI (PySide6 offscreen)
        run: |
          python - << 'PY'
          import os, sys
          os.environ["QT_QPA_PLATFORM"] = "offscreen"
          sys.path.insert(0, os.getcwd())
          import importlib
          importlib.import_module("src.ulh_desktop")
          print("OK: imported src.ulh_desktop")
          PY
